version: "3.9"

services:
  api-flask:
    image: api-flask
    container_name: api-flask
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  front-angular:
    image: front-angular
    container_name: front-angular
    build: 
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "80:80"
  mongo:
      image: mongo
      restart: always
      container_name: back-mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: nabil
        MONGO_INITDB_ROOT_PASSWORD: ainas
        MONGO_INITDB_DATABASE: backend
      volumes: 
        - "mongo_db:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://nabil:ainas@mongo:27017/

volumes:
  mongo_db:


  